### PR TITLE
Check for flag contradictions

### PR DESCRIPTION
**Pull request by djoreilly**
Check and exit if the user provides a flag and its negative.

### CODE REVIEW

**Comment by skazi0** [comment]
This is another tricky part of code in the original version.
1. most flags rely on `zypper`'s default (don't pass anything if it matches default)
2. `--[no-]recommends` has both version passed through to `zypper dup`
3. `--no-snapshots` has only negative version

**Comment by djoreilly** [comment]
> This is another tricky part of code in the original version.
> 
> 1. most flags rely on `zypper`'s default (don't pass anything if it matches default)
This commit doesn't change that.

> 2. `--[no-]recommends` has both version passed through to `zypper dup`
if that's possible with original zypper plugin, then I think we should improve it and make it impossible because zypper will fail at the last stage of the migration. It's better we fail early. Also it will simplify parsing.
```
# zypper dup --allow-vendor-change --no-allow-vendor-change
--no-allow-vendor-change used together with --allow-vendor-change, which contradict each other.
```
> 3. `--no-snapshots` has only negative version
This commit doesn't change that.

**Comment by skazi0** [comment]
but:
```
# zypper dup --no-recommends --recommends
```
is acceptable

**Comment by djoreilly** [comment]
Not on my system
```
SLEMicro3:~ # zypper dup --no-recommends --recommends
--recommends used together with --no-recommends, which contradict each other.
SLEMicro3:~ # zypper --version
zypper 1.14.46
```

**Comment by skazi0** [comment]
Yeah, the check is there since 1.14.14 (https://github.com/openSUSE/zypper/pull/205) and I tested this on 1.13.58.
If current zypper behaves like this then migration plugin accepting such conflicting flags is a bug and we should fix it instead of sticking to the original.

**Comment by skazi0** [comment]
please rebase and I'll pull this in.

**Comment by djoreilly** [comment]
> please rebase and I'll pull this in.

Done. Now we won't need to complicate the code for those corner cases.

**Pull request merged**
